spring.application.name=Ecomm_Email_Service_Application

server.port=8089

spring.kafka.bootstrap-servers=172.18.63.162:9092

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SENDER_EMAIL}
spring.mail.password=${SENDER_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true